### ISSUE TITLE
离线数据库打不开网站

### ISSUE THREAD

**Issue by TonaSmith** [tgbot-collection/YYeTsBot#11]
作者你好，我想问下，离线数据库都是人人官方的域名地址，现在已经完全打不开了。
能不能冒昧的问下，你的人人影视下载分享网站的资源数据库能不能公开啊，我想研究一下

**Comment by BennyThink** [comment]
1. `rrys2020.com` 已经打不开了没错，请看 `data`字段，里面包含了下载地址。或者你用[这个网站](https://yyets.dmesg.app/) 更方便
2. 数据库就是我分享的那个离线数据库，是公开的。除了一些优化之外，基本结构都是一样的:-)
