### ISSUE TITLE
访问

### ISSUE THREAD

**Issue by SherryLynncode** [tgbot-collection/YYeTsBot#112]
大佬，网站现在是访问不了？我打开就一直转圈圈。（2022.4.22 8.13PM）

**Comment by BennyThink** [comment]
<img width="840" alt="image" src="https://user-images.githubusercontent.com/14024832/164712355-86470871-6bca-4cc0-bfa2-02a280c0fe3c.png">



是不是你网络不太好，我刚看了没问题呢

**Comment by SherryLynncode** [comment]
它就这样在（。。）




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tgbot-collection/YYeTsBot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月22日(星期五) 晚上8:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tgbot-collection/YYeTsBot] 访问 (Issue #112)





 

 
是不是你网络不太好，我刚看了没问题呢

**Comment by BennyThink** [comment]
也许你需要挂梯子试试
