### ISSUE TITLE
chrome 访问网站确实有问题

### ISSUE THREAD

**Issue by laoxiong** [tgbot-collection/YYeTsBot#114]
环境：macOS 12.1，Chrome  100.0.4896.127，访问网站，一直显示加载中，Safri 显示正常。打开 Chrome Devtools，显示如下错误<img width="955" alt="image" src="https://user-images.githubusercontent.com/1115945/166458125-d632ad33-39cb-4431-b7d5-e66cd3f9ef2b.png">

**Comment by chicest** [comment]
> 

Chrome 100 无痕模式下可以正常进入 https://yyets.dmesg.app/home，正常模式下不行；
Firefox 和 edge 100 下正常。

请参阅：
https://hacks.mozilla.org/2022/02/version-100-in-chrome-and-firefox/

**Comment by BennyThink** [comment]
那只要删除cookie就好啦。试试看
