### ISSUE TITLE
请教一下如何打开全目录列表。谢谢

### ISSUE THREAD

**Issue by ghjkl77** [tgbot-collection/YYeTsBot#12]
你好，您说的目录列表地址 https://yyets.dmesg.app/id=index ，我尝试了好几天都打不开，提示404。因为毕竟很多剧也不知道名称，希望可以看到目录，谢谢。

**Comment by BennyThink** [comment]
https://yyets.dmesg.app/api/name?human=1

https://yyets.dmesg.app/api/name

试试这俩
