### ISSUE TITLE
一个剧为啥下了大半就停住了？

### ISSUE THREAD

**Issue by aevilorz** [tgbot-collection/YYeTsBot#13]
作者新年好。
首先，非常感谢作者拯救了人人的资源。
我现在遇到一个问题：用迅雷7下一部老剧（2013），下到某集时（73%）突然就断了。见下图
原先以为是网络的问题，挂机了几天还是一动不动，尝试下载其他的剧还是能下的。
请问这可能是什么原因？是我这边的问题还是资源不完整？
谢谢！！！
![2021-02-13_233732](https://user-images.githubusercontent.com/19884649/107854338-2d3ac080-6e56-11eb-866b-7ab44d7635f1.png)

**Comment by BennyThink** [comment]
可能是资源的问题，也许也可以尝试用下会员/新版迅雷，比如 http://songxunlei.com/

**Comment by aevilorz** [comment]
谢谢回复，迅雷会员高速下载下完了
