### ISSUE TITLE
服务器docker一键部署成功，访问正常，但是搜索不到任何本站结果，还有热搜词也没出来

### ISSUE THREAD

**Issue by dary123** [tgbot-collection/YYeTsBot#146]
服务器docker一键部署成功，访问正常，但是搜索不到任何本站结果，还有热搜词也没出来

**Comment by BennyThink** [comment]
应该修好了。再试试看
```shell
bash -c "$(curl -fsSL https://raw.githubusercontent.com/tgbot-collection/YYeTsBot/master/scripts/install.sh)"
```

**Comment by dary123** [comment]
不行，这次直接访问8888端口访问不了了，502

**Comment by dary123** [comment]
> 不行，这次直接访问8888端口访问不了了，502

不行，这次直接访问8888端口访问不了了，502

**Comment by BennyThink** [comment]
默认监听127.0.0.1，你需要改docker-compose.yml 把127去掉

**Comment by dary123** [comment]
docker-compose.yml就这么多代码

version: '3.1'

services:
  redis:
    image: redis:alpine
    restart: always
    logging:
      driver: none

  mongo:
    image: mongo
    restart: always
    volumes:
      - ./mongo_data/mongodb:/data/db
    logging:
      driver: none

  yyets-web:
    image: bennythink/yyetsbot
    restart: unless-stopped
    environment:
      - mongo=mongo
      - redis=redis
    working_dir: /YYeTsBot/yyetsweb/
    command: [ "python3","server.py","-h=0.0.0.0" ]
    ports:
      - "127.0.0.1:8888:8888"

  socat:
    image: alpine/socat

**Comment by BennyThink** [comment]
- "127.0.0.1:8888:8888"改成 - "8888:8888"

**Comment by dary123** [comment]
可以了，谢谢大佬，不过还报了一个评论列表500的错误

**Comment by dary123** [comment]
还有就是有api接口吗，我是想给app用

**Comment by BennyThink** [comment]
https://github.com/tgbot-collection/YYeTsBot/blob/master/API.md

**Comment by dary123** [comment]
感谢

**Comment by dary123** [comment]
![Dingtalk_20220906104945](https://user-images.githubusercontent.com/12826258/188537262-cd6373e7-6618-4daa-9e4b-143a3220a312.jpg)
是不是评论那边有问题，导致搜索接口500了

**Comment by dary123** [comment]
> https://github.com/tgbot-collection/YYeTsBot/blob/master/API.md

能解决不
