### ISSUE TITLE
搜索结果不带回复信息

### ISSUE THREAD

**Issue by sceraser** [tgbot-collection/YYeTsBot#147]
原内容，有一条回复信息
![image](https://user-images.githubusercontent.com/42718757/188308544-c9ea078b-cf5f-46e9-90ec-2f6dd40e0f48.png)
搜索出的结果，仅有留言本身，不带回复信息
![image](https://user-images.githubusercontent.com/42718757/188308553-4f847e68-eca0-4e0c-9505-1579ed5d4694.png)

**Comment by BennyThink** [comment]
你的搜索词，“求燕双鹰全部电视剧” 只能搜到1223368238用户的评论，这有什么问题么？

**Comment by sceraser** [comment]
> 你的搜索词，“求燕双鹰全部电视剧” 只能搜到1223368238用户的评论，这有什么问题么？

我这个例子没举好，我的意思是目前的搜索只能搜索关键词，而不能搜索对应的回复，比如我以“瑞克和莫蒂 第六季”作为关键词搜索，只能搜到一条莫名其妙的帖子，会让人以为没有下载链接
![image](https://user-images.githubusercontent.com/42718757/188418415-77a60ec6-65fb-4177-a6bc-2f37bf9f8147.png)
而实际上此条帖子是有回复并附带了链接的，只是回复内容没有带“瑞克和莫蒂”的关键词所以没被搜索到
![image](https://user-images.githubusercontent.com/42718757/188418356-77458c03-89b4-4f26-b358-08ba1bb55e07.png)
所以希望搜索结果除了索引关键词外也可以把帖子的回复内容也一并加入
![image](https://user-images.githubusercontent.com/42718757/188419805-67486815-ebb2-4360-86dc-92d71fa7d4f2.png)

**Comment by BennyThink** [comment]
搜索的结果就是针对每条评论的，暂无计划加入对这个评论的回复。

**Comment by sceraser** [comment]
> 搜索的结果就是针对每条评论的，暂无计划加入对这个评论的回复。

那能否提供留言板的楼层数从而让用户自己去找原始回复？感觉电影名字放评论，回复只有链接的情况还蛮多的，只搜索电影名的话根本找到对应的下载链接

**Comment by BennyThink** [comment]
等我有空的吧，评论楼层也有限制，没有分页。

**Comment by fengxxc** [comment]
> > 你的搜索词，“求燕双鹰全部电视剧” 只能搜到1223368238用户的评论，这有什么问题么？
> 
> 我这个例子没举好，我的意思是目前的搜索只能搜索关键词，而不能搜索对应的回复，比如我以“瑞克和莫蒂 第六季”作为关键词搜索，只能搜到一条莫名其妙的帖子，会让人以为没有下载链接 ![image](https://user-images.githubusercontent.com/42718757/188418415-77a60ec6-65fb-4177-a6bc-2f37bf9f8147.png) 而实际上此条帖子是有回复并附带了链接的，只是回复内容没有带“瑞克和莫蒂”的关键词所以没被搜索到 ![image](https://user-images.githubusercontent.com/42718757/188418356-77458c03-89b4-4f26-b358-08ba1bb55e07.png) 所以希望搜索结果除了索引关键词外也可以把帖子的回复内容也一并加入 ![image](https://user-images.githubusercontent.com/42718757/188419805-67486815-ebb2-4360-86dc-92d71fa7d4f2.png)

我这里是两条都搜得出来呦，你要不要再试试看~
![image](https://user-images.githubusercontent.com/17273344/213982297-db9c2079-0869-4f64-9465-de4667d7f7eb.png)

**Comment by BennyThink** [comment]
<img width="1093" alt="image" src="https://user-images.githubusercontent.com/14024832/215270635-0753d38c-f28c-4061-ac16-b01366188aa6.png">



修好了
