### ISSUE TITLE
win10 ubuntu 18.04 查询直接报错

### ISSUE THREAD

**Issue by Airyzf** [tgbot-collection/YYeTsBot#148]
![image](https://user-images.githubusercontent.com/27176468/188427082-6c30bd3d-5d96-452b-a82f-c46cde928385.png)

runtime error: invalid memory address or nil pointer dereference
/opt/hostedtoolcache/go/1.16.3/x64/src/runtime/panic.go:212 (0x442d1a)
/opt/hostedtoolcache/go/1.16.3/x64/src/runtime/signal_unix.go:734 (0x45b5d2)
/opt/hostedtoolcache/go/1.16.3/x64/src/database/sql/sql.go:2842 (0x535830)
/home/runner/work/YYeTsBot/YYeTsBot/yyetsweb/server.go:93 (0x8f01b0)
/home/runner/work/YYeTsBot/YYeTsBot/yyetsweb/server.go:124 (0x8f09cf)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.2/context.go:165 (0x8cc459)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.2/recovery.go:99 (0x8cc440)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.2/context.go:165 (0x8cb533)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.2/logger.go:241 (0x8cb4f2)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.2/context.go:165 (0x8c19e9)

**Comment by BennyThink** [comment]
用 Python版本的吧。Go版本是为了一键安装包临时应急准备的。

**Comment by BennyThink** [comment]
```
pip install -r requirements.txt
python server.py
```
