### ISSUE TITLE
贵网的搜索页面经常打开很慢，搜索出来是空白页面。

### ISSUE THREAD

**Issue by ghjkl77** [tgbot-collection/YYeTsBot#15]
请问是否有允许使用的时间范围，我电信网络在刚才搜索英雄，结果是空白页面。谢谢

**Comment by BennyThink** [comment]
没有任何限制的啊。是不是cf偶尔抽风？再试试看呢？


![image](https://user-images.githubusercontent.com/14024832/107897442-04a8e880-6f74-11eb-88cb-b93044e0dfab.png)
