### ISSUE TITLE
MacOS 12.6运行“一键运行包”搜索不出东西，看控制台报错了。

### ISSUE THREAD

**Issue by huangchuanal** [tgbot-collection/YYeTsBot#152]
runtime error: invalid memory address or nil pointer dereference
/Users/runner/hostedtoolcache/go/1.16.3/x64/src/runtime/panic.go:212 (0x403583a)
/Users/runner/hostedtoolcache/go/1.16.3/x64/src/runtime/signal_unix.go:734 (0x404e358)
/Users/runner/hostedtoolcache/go/1.16.3/x64/src/database/sql/sql.go:2842 (0x4125e50)
/Users/runner/work/YYeTsBot/YYeTsBot/yyetsweb/server.go:93 (0x44e4e50)
/Users/runner/work/YYeTsBot/YYeTsBot/yyetsweb/server.go:124 (0x44e566f)
/Users/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.2/context.go:165 (0x44c10f9)
/Users/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.2/recovery.go:99 (0x44c10e0)
/Users/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.2/context.go:165 (0x44c01d3)
/Users/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.2/logger.go:241 (0x44c0192)
/Users/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.2/context.go:165 (0x44b6689)
/Users/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.2/gin.go:489 (0x44b666f)
/Users/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.2/gin.go:445 (0x44b615b)
/Users/runner/hostedtoolcache/go/1.16.3/x64/src/net/http/server.go:2887 (0x42d8b22)
/Users/runner/hostedtoolcache/go/1.16.3/x64/src/net/http/server.go:1952 (0x42d3f4c)
/Users/runner/hostedtoolcache/go/1.16.3/x64/src/runtime/asm_amd64.s:1371 (0x406dbc0)

**Comment by BennyThink** [comment]
😂噗，等我有空看看修复一下……这个版本太老了

**Comment by BennyThink** [comment]
https://github.com/tgbot-collection/YYeTsBot/releases

下载最新的release试试看，会自动下载数据库。

**Comment by huangchuanal** [comment]
赞👍，问题已修复了，可以正常运行搜索了

**Comment by huangchuanal** [comment]
灰常感谢！

**Comment by BennyThink** [comment]
😇 最新的release 下有最新的UI了 欢迎试用
