### ISSUE TITLE
Bot is triggered when starting or ending group voice chat

### ISSUE THREAD

**Issue by RealFakeAccount** [tgbot-collection/YYeTsBot#17]
![image](https://user-images.githubusercontent.com/63186767/108205112-9fc7cc80-70f2-11eb-8497-48e5e896094d.png)

**Comment by BennyThink** [comment]
This shouldn't happen. I only register photo and text handlers:
```python
@bot.message_handler(content_types=["photo", "text"])
```
And according to [Telegram Document](https://core.telegram.org/bots#privacy-mode), under the following conditions the bot will receive updates:

> Privacy mode
> Bots are frequently added to groups in order to augment communication between human users, e.g. by providing news, notifications from external services or additional search functionality. This is especially true for work-related groups. Now, when you share a group with a bot, you tend to ask yourself “How can I be sure that the little rascal isn't selling my chat history to my competitors?” The answer is — privacy mode.
> 
> A bot running in privacy mode will not receive all messages that people send to the group. Instead, it will only receive:
> 
> Messages that start with a slash '/' (see Commands above)
> Replies to the bot's own messages
> Service messages (people added or removed from the group, etc.)
> Messages from channels where it's a member
> On one hand, this helps some of us sleep better at night (in our tinfoil nightcaps), on the other — it allows the bot developer to save a lot of resources, since they won't need to process tens of thousands irrelevant messages each day.
> 
> Privacy mode is enabled by default for all bots, except bots that were added to the group as admins (bot admins always receive all messages). It can be disabled, so that the bot receives all messages like an ordinary user (the bot will need to be re-added to the group for this change to take effect). We only recommend doing this in cases where it is absolutely necessary for your bot to work — users can always see a bot's current privacy setting in the group members list. In most cases, using the force reply option for the bot's messages should be more than enough.



And so in conclusion, did you set the bot as admin?

**Comment by RealFakeAccount** [comment]
> 
> 
> This shouldn't happen. I only register photo and text handlers:
> 
> ```python
> @bot.message_handler(content_types=["photo", "text"])
> ```
> 
> And according to [Telegram Document](https://core.telegram.org/bots#privacy-mode), under the following conditions the bot will receive updates:
> 
> > Privacy mode
> > Bots are frequently added to groups in order to augment communication between human users, e.g. by providing news, notifications from external services or additional search functionality. This is especially true for work-related groups. Now, when you share a group with a bot, you tend to ask yourself “How can I be sure that the little rascal isn't selling my chat history to my competitors?” The answer is — privacy mode.
> > A bot running in privacy mode will not receive all messages that people send to the group. Instead, it will only receive:
> > Messages that start with a slash '/' (see Commands above)
> > Replies to the bot's own messages
> > Service messages (people added or removed from the group, etc.)
> > Messages from channels where it's a member
> > On one hand, this helps some of us sleep better at night (in our tinfoil nightcaps), on the other — it allows the bot developer to save a lot of resources, since they won't need to process tens of thousands irrelevant messages each day.
> > Privacy mode is enabled by default for all bots, except bots that were added to the group as admins (bot admins always receive all messages). It can be disabled, so that the bot receives all messages like an ordinary user (the bot will need to be re-added to the group for this change to take effect). We only recommend doing this in cases where it is absolutely necessary for your bot to work — users can always see a bot's current privacy setting in the group members list. In most cases, using the force reply option for the bot's messages should be more than enough.
> 
> And so in conclusion, did you set the bot as admin?

No. 
![image](https://user-images.githubusercontent.com/63186767/108217806-03a5c180-7102-11eb-9f02-1cbd2b63c9cb.png)

Could we assume this question is caused by Telegram itself?

**Comment by RealFakeAccount** [comment]
upd: fixed by adding a filter
