### ISSUE TITLE
2023-1-26，无法评论，页面右上角红框报错

### ISSUE THREAD

**Issue by Rimbaud-Lee** [tgbot-collection/YYeTsBot#182]
大佬您好，2023-1-26上午无法在留言板进行评论，右上角有红框提示报错，几次报错内容分别如下，劳烦大佬有时间看一下，多谢！

> 评论出错: possible spam, reference id: 63d1ef89820d16494cbbb157
> 评论出错: possible spam, reference id: 63d1ef9d820d16494cbbb168
> 评论出错: possible spam, reference id: 63d1f06f97ab9ea2d3bafe3b
> 评论出错: possible spam, reference id: 63d1f0c3bf2b17ec80ba7a5b

![image](https://user-images.githubusercontent.com/66558377/214751178-9bf589d5-14e2-4c69-8492-b7b99ef1b367.png)

**Comment by BennyThink** [comment]
应该是被误判为spam了，我应该已经给你放出来了

**Comment by Rimbaud-Lee** [comment]
不好意思大佬，1-27上午在留言板评论还是有同样的问题，劳烦大佬有时间再看一下，这是我的id：155****1118

**Comment by BennyThink** [comment]
早上起来收到40+消息，好像都是你，都是被误判为垃圾评论了😂

**Comment by BennyThink** [comment]
等我回去把你加到白名单里，应该就没这事了

**Comment by BennyThink** [comment]
已经加好咯！从此以后你的评论不会走akismet了
