### ISSUE TITLE
我使用docker-compose 启动文件报错

### ISSUE THREAD

**Issue by biubiulu** [tgbot-collection/YYeTsBot#19]
/root/env/yyets.env is not a file.
我克隆了您的docker-compose.yml文件，在文件目录中使用了docker-compose up -d  然后提示了
/root/env/yyets.env is not a file.

**Comment by biubiulu** [comment]
后面我手动创建了提示的目录，但是仍旧报错

**Comment by BennyThink** [comment]
在与 `docker-compose.yml`同目录下，
```shell
mkdir env
touch env/yyets.env
```
然后按照这个格式填写 https://github.com/tgbot-collection/BotsRunner/blob/master/env/yyets.env

**Comment by biubiulu** [comment]
好的谢谢老baby
