### ISSUE TITLE
python库403 & 实时数据库更新

### ISSUE THREAD

**Issue by CaptainRuby** [tgbot-collection/YYeTsBot#232]
1. python库调用api提示403，好像是被cf挡了，浏览器访问api需要人工点击验证，程序api访问应该如何绕过？
2. 如果是本地部署的情况，api调用的host是不是换成localhost就可以了
3. 本地部署有什么办法可以实时更新同步在线的数据库

**Comment by BennyThink** [comment]
1. 是bug，已经修了，可能也有被cf拦住的可能，有log吗
2. 具体指哪里？本地部署的话应该是localhost就可以的
3. 没有什么实时更新的办法，只能随时下载数据库

**Comment by CaptainRuby** [comment]
@BennyThink api可以通了，但是有个接口 /api/comment/search 会报404

**Comment by BennyThink** [comment]
指的是哪里404呀，有截图吗？是release里的？还是哪里？

**Comment by CaptainRuby** [comment]
浏览器直接访问 https://yyets.dmesg.app/api/comment/search?keyword=xxx

**Comment by BennyThink** [comment]
哦。。重构的时候把这行代码删掉了。我晚上回去加一下

**Comment by CaptainRuby** [comment]
噗，原来如此，好的

**Comment by BennyThink** [comment]
<img width="864" alt="image" src="https://user-images.githubusercontent.com/14024832/234083727-cd204ebb-c028-4148-8129-3062cf4981e0.png">

fixed

**Comment by CaptainRuby** [comment]
thanks~!

**Comment by CaptainRuby** [comment]
https://yyets.dmesg.app/api/resource?keyword=权力的游戏
又被cf挡了

<!DOCTYPE html>
<html lang="en-US">

<head>
	<title>Just a moment...</title>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=Edge">
	<meta name="robots" content="noindex,nofollow">
	<meta name="viewport" content="width=device-width,initial-scale=1">
	<link href="/cdn-cgi/styles/challenges.css" rel="stylesheet">


</head>

<body class="no-js">
	<div class="main-wrapper" role="main">
		<div class="main-content">
			<noscript>
				<div id="challenge-error-title">
					<div class="h2">
						<span class="icon-wrapper">
                        <div class="heading-icon warning-icon"></div>
                    </span>
						<span id="challenge-error-text">
                        Enable JavaScript and cookies to continue
                    </span>
					</div>
				</div>
			</noscript>
			<div id="trk_jschal_js"
				style="display:none;background-image:url('/cdn-cgi/images/trace/managed/nojs/transparent.gif?ray=7c69d89568d59f67')">
			</div>
			<form id="challenge-form"
				action="/api/resource?keyword=%E6%9D%83%E5%8A%9B%E7%9A%84%E6%B8%B8%E6%88%8F&amp;__cf_chl_f_tk=kD8ixncQRpFLt9qvldRwbi6hkACQg7MYbuPQpjdPX3s-1683969841-0-gaNycGzNClA"
				method="POST" enctype="application/x-www-form-urlencoded">
				<input type="hidden" name="md" value="0nMSnOmu8qKeZMdxwOz.1umDR54PfMlqqs_dbcyfuqI-1683969841-0-ASI9YNdV0cwuwF8yifkgiNxecoOgZTG4MZyE533xlJpd-rmrxKWPexOF1bfwkE_3svfUzUJdITnWbuNiyDt1YyH9vVFMdDaqzhoYQWcH1QASLQAMsn6lglfggA-_NVHv2QPPNEmFAgLeqaZtC0sDUQq3WollhEGqKMLB6fd9zCnLZYJm25hiO-mAy7AHmmsSq_eqjeh35r1yemBtiFRTtfwa_vp_9k5im_SGwZL0ccfDDTgz5y8x0n0re3iJPDAt7yuZTHXduv9JJNf_gYlakE2QBiIM-_Kkl_oh9UW-I4xj4tPxQ1lGxhJimqDSeF-xBcd4dO5XyzuC70v2E-aCxQpksztYjMqE6Ol0CGNmA7fBSbRMJtVeMdxZxVhpn3nPy0UVJAanbUlHXMGim-AU_cKz3W6W7C9XaDf2mGRtQg7QvbInZXUkaPgw2gow9IOCftG1jvmHcBLiyDhhZWxdmjICvNU2dYUNZEzXONj6sZaADThTkqm-ZmsfVeAXj_JbxzZ-90SxG4FTtQrPRgpzCZdbCruNNjRHSkivI4kZ-sK4fg_xENx6oK9DbL_W4G9wzp0klBEVAIQ3erZy2Xw3ZmTP3AH6Q77JDPGLtqvUQnkO6aGa7kt-0ZtjWueYtzHQHRU5BZir_yN2s6hfmtx2qy26lmYELG3dqpnlxZjsyKyemdTNlY5ioReEo4lxAm2r0FuMWg-sfLOy85kfVwPD2iwsBDuKpR4HjC_sHBhecEJVMuQy1uyqlPBskTzAU1nCBN-kb5oWINO-aZfOqixKS_jSM67Vm_xrETqSg5lfdW_sHGGwXSielBTzFVrsq4WGL8ppcOyMwTjZtWt3rIK85NT4hT5Ts0fqNbO3Tu6kh8uhyFMqITT1ULBKVIKwa59hqUDfHnWY_SO7A_CSeLYsyKCUTKPhce-mvRNJwHl2Ifcz8W5tm6cSEaB-eq98akN-vnnerqOgdvc5qRNHNfL7a3Av5bkI2gydb3HNOFDJURfhlX1nopNd65_HWeRYnlCTYGARmK7vl3vazbl6eMwOEyszUv6VCW3Zgkb2dOx5wTTtW8YyP0jsUap3B44SFQuVJm4BytC5F1yevjNf-KYvDLQ3bNxy07VfhFlv0X2djAUZhDLazPwJTs0Gw-Vlh2f9yvcZVOZW6_miVCCsIvELcl3VBrWFvVXd6yYQCLh7nA-TR219tb6HZmlFyIQrfpJ4aDBPdIlAC0HEh_ReVXAWQtltx7FtWyzX4IW0Xq3E2B4zyaZuzXkzBfr1iULPf3McnKzXMz3P46rzvJxJvA7Hk_5_qaTPYUDiKPXhWB7PLTbpawXt1rdQ-E-qXc-5AZ93e8JO2ODCdpSVg4zuzQ7jAlfPKYXkcrSzgkrxekBDRybAXJZ5Vb4RWG9W1c2SP4zz71sq55Bu-ShAQNAUA7xPNt_HnxJO-vTn_RMCeLHF_42j6-W6pJMLrUlgE848hU2Mf8ZB1EYQJCej0BsJ2R1x0co2_J6zvrl8JILPghDhy9q9TI4n47wb6FOrUIFshMShjgffR-PWBUCmVGYc2frJgBrGpVT392YoXx3lPIl6gv6MR8XpnrgZAhFn1BDMbc03SDCECX561Vjb-hok7L9AedELEPA6YhMCNuB_FrDeu9rXosJ3VYj08YgxsC8BvEGld_7A_CXzQxcQbiF_IGpBrI6GvRM8fGE96OtzCaPNGrVeFaxn3d90327spxZsxFW2xPhdegzsydFVK6PCecenlxBO0BsrMTsiyeWGDE7KW8arn_nEAi4Y-s0PX6aV2iVGayCiVfOssxPHsLv9_eC_IYTUIpRxhVcP6o50_quxXH0NiAHj4wDjZQq9ZXp1MTdXrohert7gYK3dKXS5HUdd718F87ZDn0HdoaFH2NuU9WQ2vOjvFdIuG7SBDAEdxSK28ZGPUkGVui21Qt7hEDBQw2tQbhcTrplV3UE11QmpksueZua_1Fpl8Pn6y1BKBexpfkmsQ9MrIo1eBVIlOnJINe9XMv5ylHBekF4_EWtJBQlN0zWNbpDngFz6pH0COnqX8BQte4-3E9NcoxR055rXZVa372lZ6OR2N5wHiru872t5DEZ7tJCsCL8oTrGVeL5YzCvF3Pmk6Gbhsr-0jrquyeyn_5eoeGLLTyMAEzuyNUotHnAKnkl6SEb_wf0FvDhiX--UwDKTjg7tExbsH_J-92wbomziajHanUaiBPMGpPHBpqXfJcEdntdfT6KT2hmQsbQZvznIkNd6lqMQ5yOm4HnImzhZngnAd-PPxs_y-djof9YD9efHwolCsmG0hxmoPGxlymaTMv3cFYbHP1TkFa4gQwJe_dHT49EKoJQcOEtgD6zERHh1osue7ImAgjfWbwTvVHlGdw2_YOoxSzRK1aKlRzVyDrfGXndQQ-_6jlRkf5wz74ONoVsvgFkzujFfudrhW64vvfdqp08dY645jD2kiLE5A-qhZJFIrGP0fYrwKg-UZrlnDWRvusxtVwRWp4wPnmwqZrJA_xDsWXuJ2vEjjnA3GL1zWVoMDuCkAKqKFXK9Vpel7QnoCif9h-fVWgde1sr83tnqzmt8nZmn2m0">
        </form>
		</div>
	</div>
	<script>
		(function(){
        window._cf_chl_opt={
            cvId: '2',
            cZone: 'yyets.dmesg.app',
            cType: 'managed',
            cNounce: '3580',
            cRay: '7c69d89568d59f67',
            cHash: '13f71a278de0abf',
            cUPMDTk: "\/api\/resource?keyword=%E6%9D%83%E5%8A%9B%E7%9A%84%E6%B8%B8%E6%88%8F&__cf_chl_tk=kD8ixncQRpFLt9qvldRwbi6hkACQg7MYbuPQpjdPX3s-1683969841-0-gaNycGzNClA",
            cFPWv: 'g',
            cTTimeMs: '1000',
            cMTimeMs: '0',
            cTplV: 5,
            cTplB: 'cf',
            cK: "",
            cRq: {
                ru: 'aHR0cHM6Ly95eWV0cy5kbWVzZy5hcHAvYXBpL3Jlc291cmNlP2tleXdvcmQ9JUU2JTlEJTgzJUU1JThBJTlCJUU3JTlBJTg0JUU2JUI4JUI4JUU2JTg4JThG',
                ra: 'UG9zdG1hblJ1bnRpbWUvNy4zMi4y',
                rm: 'R0VU',
                d: 'B2kWmwaw3c3LG9F4WH88fyJZ0hGt0PMAlp040uLIrVKJxMU6nVpsz9B90xtcX2WhRjFBGKpUy+2e7P2lfRRVzWdD2mVz+HBMc1K7WXmSjTyiV47GBfnj+Fk1LXynwCprqdfk+ep691ZfJN0OdDdYgN/k7lVhNtozvMsEz5SanzXeVEm8sMOAAsXA4JtpM9bLcZjtsAE7YE+PXHn5dB38WQx9olBlxx0Qaq13hQIB7RuSUe6ocNGkMnOrwun0ClgK2gDMCsqAclWw7QOCvxIKrNn13j5Lh/1AtlCRjqv/cImb2NHSlF5RIAl2xx++MsZBDdT3w6CcCo1hlqiyhEM1KBsIoDXa9ghhI6yooYf5OgKwlbTkEwhrsl2oWHErxI0pDeztZqH63eltnrl6i/M2qIf7M6JlP6sh4AHAKyFXM4IlJO383tayUix2rqZCMWSv+znoxXdRx+Vo3UemNTrg/yJGJtRo7JfT3HlFK3dt9N5ErIf2/g0dCY344pd4tMLR7QtArGwAP8uZpvMcK1WegbwQi7Te2hOcDnbtRbU0EPovRFtd1KY4fVZ1dQ/Cdl/c0h5wRSXiEV/ieq6uJNF0AiMuA7wRoJZ1G4ala+cGJ7+kz3VymqDhZPGek6lW5pPI',
                t: 'MTY4Mzk2OTg0MS41MDkwMDA=',
                m: 'RR1K5pqb/IZNAG5E9rZMLv5zRUZn+MSU+d5gJ3ckuM0=',
                i1: 'K/HmthLMEZPg849mL7zOng==',
                i2: 'sKPOUFA3eG18FaNmZZjZnQ==',
                zh: 'JxxVLc/bxK1erRpn9moWkrjYLE8ru3w5dKtciLi2gdw=',
                uh: 'kg2XhtCuHyOZw45HjPkBG1FasBIldVNSGlbKvVJNn6o=',
                hh: 'Fp6OyHSj/S/TK7jFX6xbThJF5So397HRi5w0pcfv9Ww=',
            }
        };
        var trkjs = document.createElement('img');
        trkjs.setAttribute('src', '/cdn-cgi/images/trace/managed/js/transparent.gif?ray=7c69d89568d59f67');
        trkjs.setAttribute('alt', '');
        trkjs.setAttribute('style', 'display: none');
        document.body.appendChild(trkjs);
        var cpo = document.createElement('script');
        cpo.src = '/cdn-cgi/challenge-platform/h/g/orchestrate/managed/v1?ray=7c69d89568d59f67';
        window._cf_chl_opt.cOgUHash = location.hash === '' && location.href.indexOf('#') !== -1 ? '#' : location.hash;
        window._cf_chl_opt.cOgUQuery = location.search === '' && location.href.slice(0, location.href.length - window._cf_chl_opt.cOgUHash.length).indexOf('?') !== -1 ? '?' : location.search;
        if (window.history && window.history.replaceState) {
            var ogU = location.pathname + window._cf_chl_opt.cOgUQuery + window._cf_chl_opt.cOgUHash;
            history.replaceState(null, null, "\/api\/resource?keyword=%E6%9D%83%E5%8A%9B%E7%9A%84%E6%B8%B8%E6%88%8F&__cf_chl_rt_tk=kD8ixncQRpFLt9qvldRwbi6hkACQg7MYbuPQpjdPX3s-1683969841-0-gaNycGzNClA" + window._cf_chl_opt.cOgUHash);
            cpo.onload = function() {
                history.replaceState(null, null, ogU);
            };
        }
        document.getElementsByTagName('head')[0].appendChild(cpo);
    }());
	</script>


</body>

</html>

**Comment by BennyThink** [comment]
😓又被挡了啊，这个很难搞，谁也不知道cf背后的逻辑是什么。要不我给你加个白名单，你的请求IP、UA或者什么我们可以约定好一个

**Comment by CaptainRuby** [comment]
因为我挂代理访问的，所以ip会变，我加个请求头：headers.set("User", "CaptainRuby"); 你用这个识别怎样

**Comment by BennyThink** [comment]
邮件发给我请求头，避免公开渠道发
