### ISSUE TITLE
英文搜索不支持忽略大小写匹配

### ISSUE THREAD

**Issue by NewtMa** [tgbot-collection/YYeTsBot#25]
先谢谢作者的贡献, 拯救了单身狗的无数个夜晚wwwwww

**Comment by BennyThink** [comment]
![image](https://user-images.githubusercontent.com/14024832/115860472-1fac4300-a464-11eb-8d01-9b169b2eac23.png)

支持的呀。你搜索的是什么

**Comment by NewtMa** [comment]
哦，我没写+号，我直接写的"sound of metal"，然后我只好找中文，发现英文是"Sound of Metal"😂😂

**Comment by BennyThink** [comment]
和有没有加号其实没关系，是应该能搜索到的哦。

**Comment by NewtMa** [comment]
![Screenshot_2021-04-24-20-43-01-319_org telegram messenger](https://user-images.githubusercontent.com/48610536/115959299-214a3980-a53e-11eb-8436-a529830387fd.png)
我说的是tg的bot不是网页啦

**Comment by NewtMa** [comment]
@BennyThink

**Comment by BennyThink** [comment]
晕 原来是bot
