### ISSUE TITLE
速度与激情9的资源页显示空白+docker详细教程

### ISSUE THREAD

**Issue by mawanglin** [tgbot-collection/YYeTsBot#30]
1.首页的《速度与激情9》点进去资源页显示为空白；
2.能否增加一份详细的docker版本的使用说明，谢谢；

**Comment by BennyThink** [comment]
1. 因为速度与激情9是5月21日大陆上映的，那个时候人人影视都凉了快半年了
2. https://github.com/tgbot-collection/YYeTsBot/blob/master/DEVELOPMENT.md
