### ISSUE TITLE
我的资源结果页是一片空白

### ISSUE THREAD

**Issue by kita0531** [tgbot-collection/YYeTsBot#31]
您好，真的非常感激您制作的开源网页，帮助我找到了很多想要珍藏的影视作品，但是以下几部资源我的搜索结果页面是空白的，根据您所留的联系方式，我在此写下issue，劳烦您看一下，谢谢！
https://yyets.dmesg.app/resource.html?id=37140
https://yyets.dmesg.app/resource.html?id=37137
https://yyets.dmesg.app/resource.html?id=37138
https://yyets.dmesg.app/resource.html?id=37139

**Comment by BennyThink** [comment]
这个系列人人影视本身也应该没有，看了返回的数据是空，所以页面打开是空白。
