### ISSUE TITLE
请问这个是什么问题啊？

### ISSUE THREAD

**Issue by backuponeday** [tgbot-collection/YYeTsBot#44]
![image](https://user-images.githubusercontent.com/86595988/123747382-719a9a80-d8e5-11eb-8e53-3287f85785ba.png)

**Comment by BennyThink** [comment]
需要redis。
# 解决方法1
1. 下载安装redis https://github.com/dmajkic/redis https://www.memurai.com/
2. 更改hosts 加一行 `redis 127.0.0.1` 

# 解决方法2
```
set DISABLE_REDIS=1
python3 server .py
```

**Comment by backuponeday** [comment]
这个 set DISABLE_REDIS=1 是环境变量吗？

**Comment by backuponeday** [comment]
谢谢，问题解决了
