### ISSUE TITLE
请问有所有字幕的下载链接嘛？

### ISSUE THREAD

**Issue by SFUMECJF** [tgbot-collection/YYeTsBot#46]
非常非常感谢大佬的资源！已经点star捐款了！

请问大佬，哪有所有字幕的下载链接嘛？我看到的都是视频的。

**Comment by BennyThink** [comment]
没爬字幕……

**Comment by OkayPJ** [comment]
人人影视似乎没有在网站上发布过字幕吧……
[SubHD](https://subhd.tv/zu/14) 上可以找到一些

**Comment by SFUMECJF** [comment]
好的！感谢两位大佬。那我没问题了。嘿嘿
