### ISSUE TITLE
感谢救星！

### ISSUE THREAD

**Issue by rilyuuj** [tgbot-collection/YYeTsBot#5]
其实这也不算issue啦，就是特地来给作者star的
首先当然是感谢作者！真是广大网民的救星！一路从微博追到coolapk评论到tg，后悔应该早点来gayhub的:(
之后不管yy之后会怎么样，互联网精神还是会传承滴！
工具很好用，作者真是有钞能力，备份这些资源要花的不少了，想起了当年备份eh事件。建议挂上捐助入口，涓涓细流汇聚成海嘛~另外希望bot能增加“索引”功能，只要标题即可，分类可以沿用原来rr的，不需要图片，服务器压力会小一点。
最后希望作者能开个tg或者dc群，能让广大爱好者相互~~吹水尬聊~~分享讨论^^

**Comment by BennyThink** [comment]
感谢支持！

1. 捐助的事情嘛，没有太好的办法，既然不想微信支付宝，那就比较麻烦，门槛比较高。有个star就可以了。
2. bot索引功能，可能你指得是[这里](https://yyets.dmesg.app/)，用这个更好？
3. 服务器其实0压力，每个月都在吃灰浪费😂
3. 有[Telegram Channel](https://t.me/mikuri520)以及附属的群可以水

**Comment by rilyuuj** [comment]
感谢回复！
我的意思最好能有一个列表页面把能把yy之前的资源按年份或者类型的分类的，方便查找旧资源，就像TGCNbot那样。
当然，搜索页面也很好用！

**Comment by BennyThink** [comment]
很想，但是……
```json
{
                "id" : 34812,
                "cnname" : "逃避可耻却有用",
                "enname" : "NIGERUHA HAJIDAGA YAKUNITATSU",
                "aliasname" : "逃避虽可耻但有用 / 雇佣妻子(港) / 月薪娇妻(台) / 逃跑是可耻但是有用 / 逃避虽可耻但很有用 / 逃避可耻但有用",
                "channel" : "tv",
                "channel_cn" : "日剧",
                "area" : "日本",
                "show_type" : "",
                "expire" : "1610399344",
                "views" : "0"
            }

```

并没有分类数据，只有channel
