### ISSUE TITLE
5.0.2导入数据库失败

### ISSUE THREAD

**Issue by chenxihub** [tgbot-collection/YYeTsBot#58]
![image](https://user-images.githubusercontent.com/34295619/133230687-e894d29b-d26d-4b01-83d0-e29535716eae.png)
![image](https://user-images.githubusercontent.com/34295619/133230733-15853d50-74b0-4d62-b8bf-8fa47ed34f39.png)

**Comment by BennyThink** [comment]
清空数据库后重新导入。
