### ISSUE TITLE
网页打不开了

### ISSUE THREAD

**Issue by xifeng0** [tgbot-collection/YYeTsBot#59]
提示 

该网站yyets.dmesg.app/目前处于离线状态。Cloudflare 的 Always Online™显示了来自Internet Archive 的 Wayback Machine的此网页的快照。要检查实时版本，请单击刷新。

**Comment by BennyThink** [comment]
谢谢提醒，昨晚不知道为什么所有容器突然卡住了。我今天弄一个检测功能吧
