### ISSUE TITLE
感谢作者的无私分享，提点小建议。

### ISSUE THREAD

**Issue by ghjkl77** [tgbot-collection/YYeTsBot#6]
当然作品已经很好了，使用也很方便，就是在搜索时，一个名字会搜索出很多同名的作品，若有时间的话，能否按照原来的资讯页面建立分类，按照年度、国家、类型来区分同名的作品。不改也没关系，很感谢作者的努力。另外磁力网站里面的链接也都全部备份了吗？因为里面有很多初版的文件，在主站上洗版后，主站只留下最后更新的文件，之前的比如DVD版，TV版，初版翻译的都只留在磁力网站上，有时间也话，给mag网站也做一个全站备份库吧，谢谢。

**Comment by rilyuuj** [comment]
> 当然作品已经很好了，使用也很方便，就是在搜索时，一个名字会搜索出很多同名的作品，若有时间的话，能否按照原来的资讯页面建立分类，按照年度、国家、类型来区分同名的作品。不改也没关系，很感谢作者的努力。另外磁力网站里面的链接也都全部备份了吗？因为里面有很多初版的文件，在主站上洗版后，主站只留下最后更新的文件，之前的比如DVD版，TV版，初版翻译的都只留在磁力网站上，有时间也话，给mag网站也做一个全站备份库吧，谢谢。

这个我之前提过，主要是现有爬来的的没有这个分类表，要做的话就要重新做数据库表了

**Comment by BennyThink** [comment]
😨楼上解答了你的问题。磁力站不太好爬，没有明显的特征，并且他太慢了。
