### ISSUE TITLE
留言板的资源有些不能直接搜索到

### ISSUE THREAD

**Issue by THTye** [tgbot-collection/YYeTsBot#61]
不知道能不能稍微优化以下，可以直接从主页搜索到留言的资源，谢谢

**Comment by BennyThink** [comment]
![image](https://user-images.githubusercontent.com/14024832/142834031-57ba2275-cfb3-4aee-9292-b798b3897317.jpeg)


这不是吗？

**Comment by THTye** [comment]
你好，你看下我的图，比如这种就搜不到，不知怎么回事
![火狐截图_2021-11-22T11-55-37 829Z](https://user-images.githubusercontent.com/6628607/142858030-66a74d9b-3cc5-4393-abd6-4b2aeea4e2a5.png)
![火狐截图_2021-11-22T11-56-44 334Z](https://user-images.githubusercontent.com/6628607/142858047-d38d99e1-4933-42df-b64c-b999374534ac.png)
![火狐截图_2021-11-22T11-57-09 407Z](https://user-images.githubusercontent.com/6628607/142858059-369f3ccb-b562-4799-a03e-719f81eef0f5.png)

**Comment by BennyThink** [comment]
OK看起来像是bug……有空我来修一下

**Comment by BennyThink** [comment]
![image](https://user-images.githubusercontent.com/14024832/143678974-1b29c11f-3bc0-4bf9-8dba-638c62c44f4b.png)

好了

**Comment by THTye** [comment]
谢谢
