### ISSUE TITLE
你好，再次感谢作者的无私奉献，询问能否弄个全站的目录列表。

### ISSUE THREAD

**Issue by ghjkl77** [tgbot-collection/YYeTsBot#7]
之前剧慌时，也不知道看什么好，都是看列表更新或推荐什么的。
现在想在不知道剧名的情况下，自行翻看查找。想询问一下，是否有yyets的全部目录列表文档可以查看，谢谢。

**Comment by BennyThink** [comment]
➡️ https://yyets.dmesg.app/id=index

**Comment by BennyThink** [comment]
#12
