### ISSUE TITLE
网站卡死，无法打开

### ISSUE THREAD

**Issue by 248615** [tgbot-collection/YYeTsBot#95]
因为人人影视及资源分享站停止注册账户的原因，我想登陆原账号时，发生了网站卡死，无法打开等问题，有望benny解决
![Uploading D909F9F5-1ADB-4CD8-98A3-F1EF3DD77661.png…]()

**Comment by BennyThink** [comment]
嗯……你这个问题很迷，你用的是什么浏览器？有图吗

**Comment by 248615** [comment]
> 嗯......你这个问题很迷，你用的是什么浏览器？有图吗？

试过三个浏览器：Safari、百度、夸克，无一例外在我登陆账号时发生了网站白屏的问题，刷新后都无法再打开了
以下是图片：
![8BF6A0DD-8CBC-43B3-BDA3-CCBDAF855D14](https://user-images.githubusercontent.com/102470371/160285323-a68cbbeb-1ae3-49a0-b120-
![B859FDEB-CD03-4F1D-AE69-78504F7A5A99](https://user-images.githubusercontent.com/102470371/160285350-66fb5ef0-8070-41e6-9bce-7ce229ea069f.png)
812c0472875f.png)

**Comment by BennyThink** [comment]
哎这，要不要试试Chrome？能排除网络原因吗？

**Comment by 248615** [comment]
> 哎这，要不要试试Chrome？能排除网络原因吗？我改天试试排查看看

完全可以排除网络原因，我已重启设备一次、换网3次，无一例外都会出现该问题。我会再去试试chrome的，谢谢Benny！

**Comment by BennyThink** [comment]
嗯 另外建议PC上也试试看

**Comment by MissLeely** [comment]
你是在非洲上的网吗。

**Comment by 248615** [comment]
> 嗯 另外建议PC上也试试看

chrome、pc的网站均能正常进入，唯独不能登陆账号（登陆了账号就和之前一样白屏，网站不能打开）
最近登陆账号我得慎重考虑😂

**Comment by 248615** [comment]
> 你是在非洲上的网吗。

应该是的，我这运气确实蛮“非酋”了🌚

**Comment by Mcgrady2009** [comment]
一样的问题，换了不同的电脑，chrome和Edge浏览器。

**Comment by BennyThink** [comment]
无法复现。你们俩的账号是什么？

https://user-images.githubusercontent.com/14024832/160510209-ad3dc3d5-e823-49f6-a5be-f4eb3d18a03e.mp4

**Comment by Mcgrady2009** [comment]
> 

mcgrady2009@vip.qq.com

**Comment by Mcgrady2009** [comment]
> 无法复现。你们俩的账号是什么？
> 
>  1.mp4


https://user-images.githubusercontent.com/21356307/160511100-c01449a1-409b-48ae-a08d-32f0933cf0ae.mp4

**Comment by yzs0324** [comment]
> 嗯……你这个问题很迷，你用的是什么浏览器？有图吗

我也是，页面一直在转圈圈

**Comment by BennyThink** [comment]
哦豁 看来是个前端的bug ……

**Comment by yihong0618** [comment]
刷新下 cache 试试？也可以不带 cookie 用隐私模式试试看看能否解决问题。

**Comment by yzs0324** [comment]
> 

把cookie删掉后能打开了

**Comment by yihong0618** [comment]
> > 
> 
> 把cookie删掉后能打开了

cool

**Comment by 248615** [comment]
cookie删了能打开，就是不能登陆账号

**Comment by BennyThink** [comment]
见了鬼了，始终无法复现啊😂

**Comment by BennyThink** [comment]
应该已经修复了，重新登录再试试看？

**Comment by Mcgrady2009** [comment]
> 应该已经修复了，重新登录再试试看？

可以了，感谢。
