### ISSUE TITLE
大佬好，网站进不去，删除cookie就好了，请查明原因

### ISSUE THREAD

**Issue by ke-nan** [tgbot-collection/YYeTsBot#96]
如题

**Comment by BennyThink** [comment]
参考一下#95 你也是登录了就不行？能把cookie发我吗？这个域名的就可以

**Comment by ke-nan** [comment]
> 参考一下#95 你也是登录了就不行？能把cookie发我吗？这个域名的就可以

对，之前登录过。cookie怎么发，不懂哎

**Comment by ke-nan** [comment]
> 参考一下#95 你也是登录了就不行？能把cookie发我吗？这个域名的就可以

我google一下，大佬等我

**Comment by BennyThink** [comment]
好的感谢，只要 yyets.dmesg.app 的，其他千万不要发给我。应该有个username。

打开网站，登录，确保白屏，然后按F12，console里输入 document.cookie 复制给我就可以

或者像下图一样手动复制粘贴
<img width="428" alt="image" src="https://user-images.githubusercontent.com/14024832/160820130-283d77c8-53b8-41c8-90c7-0df49655ec2f.png">


另外在这里 Local Storage，如果能有也最好了

<img width="1281" alt="image" src="https://user-images.githubusercontent.com/14024832/160821253-7811b8e3-7973-401a-98c5-0f8226d2509c.png">

**Comment by ke-nan** [comment]
> 参考一下#95 你也是登录了就不行？能把cookie发我吗？这个域名的就可以

username=2|1:0|10:1648638396|8:username|4:bmFu|82011fe7017d0884e7454ab0d86b1706d9562994bad7337c76d08e1577f812cf

浏览器控制台上查看的，不知道你要的是不是这个

**Comment by ke-nan** [comment]
> 参考一下#95 你也是登录了就不行？能把cookie发我吗？这个域名的就可以

怎么私发你，不清楚直接发这里安全不😂

**Comment by BennyThink** [comment]
对的直接发不太好，邮件吧 benny.think@gmail.com
