### ISSUE TITLE
类似#95#96，登录后无法正常显示。

### ISSUE THREAD

**Issue by 9hrs4real** [tgbot-collection/YYeTsBot#98]
很久没有登陆过了，然后登录后变成如图所示：
![01](https://user-images.githubusercontent.com/102840808/161361842-24bf5ccc-e70d-4cde-8aa8-806ec1f181ae.gif)
发现快速点击4次刷新会出现如图所示情况：1.右上角出现提示 2.成功显示网站 3.右上角显示为登录状态 4.但是下面不能显示公告/更新/评论，点击开始使用会变成白屏。
![02](https://user-images.githubusercontent.com/102840808/161362247-3d26ef7e-0480-43be-bf39-bcfb66d0c094.gif)
![03](https://user-images.githubusercontent.com/102840808/161362264-ba979123-0076-459b-bc4e-9edc3305ceca.png)
![04](https://user-images.githubusercontent.com/102840808/161362267-b37baf29-91e8-4b78-ad7c-9ebce32d365a.png)
（设备为win10的Chrome100，在安卓Chrome100里的情况一模一样，包括快速刷新后的结果，包括wifi换成手机流量，包括匿名窗口。）

**Comment by BennyThink** [comment]
应该已经修复了，重新登录再试试看？

**Comment by 9hrs4real** [comment]
> 应该已经修复了，重新登录再试试看？

已修复，感谢。
